name: Scaffold UniTrader-RL
on:
  workflow_dispatch:

permissions:
  contents: write
  workflows: write       # → 仍要保留

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout 用 PAT，而且關掉 persist-credentials
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}        # ← 用你的 PAT
          persist-credentials: false       # ← 不要把預設 token 寫進 repo

      # 2) Python
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install --upgrade pip

      - name: Run scaffold
        run: python scaffold.py

      # 3) Auto-commit 也指定 PAT
      - name: Auto commit generated files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.PAT }}   # ← 一定要這行
          commit_message: "🛠️ init UniTrader-RL scaffold"
          branch: main
          file_pattern: |
            **/*
